# Sadece geliştirme ortamı için kullanın

x-logging: &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

services:
  traefik:
    image: traefik:2.11
    container_name: appconda-traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.file.directory=/storage/config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`,`appconda`)
      - --entrypoints.appconda_web.address=:80
      - --entrypoints.appconda_websecure.address=:443
      - --accesslog=true
    ports:
      - 80:80
      - 8080:80
      - 443:443
      - 9500:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appconda-config:/storage/config:ro
      - appconda-certificates:/storage/certificates:ro
    depends_on:
      - appconda
    networks:
      - gateway
      - appconda

  appconda:
    container_name: appconda
    <<: *x-logging
    image: appconda-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9501:80
    networks:
      - appconda
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label-stack=appconda"
      - "traefik.docker.network=appconda"
      - "traefik.http.services.appconda_api.loadbalancer.server.port=80"
      #http
      - traefik.http.routers.appconda_api_http.entrypoints=appconda_web
      - traefik.http.routers.appconda_api_http.rule=PathPrefix(`/`)
      - traefik.http.routers.appconda_api_http.service=appconda_api
      # https
      - traefik.http.routers.appconda_api_https.entrypoints=rappconda_websecure
      - traefik.http.routers.appconda_api_https.rule=PathPrefix(`/`)
      - traefik.http.routers.appconda_api_https.service=appconda_api
      - traefik.http.routers.appconda_api_https.tls=true
    volumes:
      - appconda-uploads:/storage/uploads:rw
      - appconda-cache:/storage/cache:rw
      - appconda-config:/storage/config:rw
      - appconda-certificates:/storage/certificates:rw
      - appconda-functions:/storage/functions:rw
      - ./src:/usr/app/src
    depends_on:
      - mariadb
      - redis
      # - clamav
    entrypoint:
      - npm
      - run
      - pm2
    environment:
      - _APP_ENV
      - _APP_EDITION
      - _APP_WORKER_PER_CORE
      - _APP_LOCALE
      - _APP_CONSOLE_WHITELIST_ROOT
      - _APP_CONSOLE_WHITELIST_EMAILS
      - _APP_CONSOLE_WHITELIST_IPS
      - _APP_CONSOLE_HOSTNAMES
      - _APP_SYSTEM_EMAIL_NAME
      - _APP_SYSTEM_EMAIL_ADDRESS
      - _APP_EMAIL_SECURITY
      - _APP_SYSTEM_RESPONSE_FORMAT
      - _APP_OPTIONS_ABUSE
      - _APP_OPTIONS_ROUTER_PROTECTION
      - _APP_OPTIONS_FORCE_HTTPS
      - _APP_OPTIONS_FUNCTIONS_FORCE_HTTPS
      - _APP_OPENSSL_KEY_V1
      - _APP_DOMAIN
      - _APP_DOMAIN_TARGET
      - _APP_DOMAIN_FUNCTIONS
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_SMTP_HOST
      - _APP_SMTP_PORT
      - _APP_SMTP_SECURE
      - _APP_SMTP_USERNAME
      - _APP_SMTP_PASSWORD
      - _APP_USAGE_STATS
      - _APP_STORAGE_LIMIT
      - _APP_STORAGE_PREVIEW_LIMIT
      - _APP_STORAGE_ANTIVIRUS
      - _APP_STORAGE_ANTIVIRUS_HOST
      - _APP_STORAGE_ANTIVIRUS_PORT
      - _APP_STORAGE_DEVICE
      - _APP_STORAGE_S3_ACCESS_KEY
      - _APP_STORAGE_S3_SECRET
      - _APP_STORAGE_S3_REGION
      - _APP_STORAGE_S3_BUCKET
      - _APP_STORAGE_DO_SPACES_ACCESS_KEY
      - _APP_STORAGE_DO_SPACES_SECRET
      - _APP_STORAGE_DO_SPACES_REGION
      - _APP_STORAGE_DO_SPACES_BUCKET
      - _APP_STORAGE_BACKBLAZE_ACCESS_KEY
      - _APP_STORAGE_BACKBLAZE_SECRET
      - _APP_STORAGE_BACKBLAZE_REGION
      - _APP_STORAGE_BACKBLAZE_BUCKET
      - _APP_STORAGE_LINODE_ACCESS_KEY
      - _APP_STORAGE_LINODE_SECRET
      - _APP_STORAGE_LINODE_REGION
      - _APP_STORAGE_LINODE_BUCKET
      - _APP_STORAGE_WASABI_ACCESS_KEY
      - _APP_STORAGE_WASABI_SECRET
      - _APP_STORAGE_WASABI_REGION
      - _APP_STORAGE_WASABI_BUCKET
      - _APP_FUNCTIONS_SIZE_LIMIT
      - _APP_FUNCTIONS_TIMEOUT
      - _APP_FUNCTIONS_BUILD_TIMEOUT
      - _APP_FUNCTIONS_CPUS
      - _APP_FUNCTIONS_MEMORY
      - _APP_FUNCTIONS_RUNTIMES
      - _APP_EXECUTOR_SECRET
      - _APP_EXECUTOR_HOST
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG
      - _APP_MAINTENANCE_INTERVAL
      - _APP_MAINTENANCE_RETENTION_EXECUTION
      - _APP_MAINTENANCE_RETENTION_CACHE
      - _APP_MAINTENANCE_RETENTION_ABUSE
      - _APP_MAINTENANCE_RETENTION_AUDIT
      - _APP_MAINTENANCE_RETENTION_USAGE_HOURLY
      - _APP_MAINTENANCE_RETENTION_SCHEDULES
      - _APP_SMS_PROVIDER
      - _APP_SMS_FROM
      - _APP_GRAPHQL_MAX_BATCH_SIZE
      - _APP_GRAPHQL_MAX_COMPLEXITY
      - _APP_GRAPHQL_MAX_DEPTH
      - _APP_VCS_GITHUB_APP_NAME
      - _APP_VCS_GITHUB_PRIVATE_KEY
      - _APP_VCS_GITHUB_APP_ID
      - _APP_VCS_GITHUB_WEBHOOK_SECRET
      - _APP_VCS_GITHUB_CLIENT_SECRET
      - _APP_VCS_GITHUB_CLIENT_ID
      - _APP_MIGRATIONS_FIREBASE_CLIENT_ID
      - _APP_MIGRATIONS_FIREBASE_CLIENT_SECRET
      - _APP_ASSISTANT_OPENAI_API_KEY
      - _APP_MESSAGE_SMS_TEST_DSN
      - _APP_MESSAGE_EMAIL_TEST_DSN
      - _APP_MESSAGE_PUSH_TEST_DSN
      - _APP_CONSOLE_COUNTRIES_DENYLIST
      - _APP_EXPERIMENT_LOGGING_PROVIDER
      - _APP_EXPERIMENT_LOGGING_CONFIG
      - _APP_DATABASE_SHARED_TABLES

  appconda-worker-audits:
    entrypoint: worker-audits
    <<: *x-logging
    container_name: appconda-worker-audits
    image: appconda-dev
    networks:
      - appconda
    volumes:
      - appconda-uploads:/storage/uploads:rw
      - appconda-cache:/storage/cache:rw
      - appconda-config:/storage/config:rw
      - appconda-certificates:/storage/certificates:rw
      - appconda-functions:/storage/functions:rw
      - ./src:/usr/app/src
    depends_on:
      - redis
      - mariadb
    environment:
      - _APP_ENV
      - _APP_WORKER_PER_CORE
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG
      - _APP_DATABASE_SHARED_TABLES

  mariadb:
    image: mariadb:10.7 # fix issues when upgrading using: mysql_upgrade -u root -p
    container_name: appconda-mariadb
    <<: *x-logging
    networks:
      - appconda
    volumes:
      - appconda-mariadb:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
      - MYSQL_DATABASE=${_APP_DB_SCHEMA}
      - MYSQL_USER=${_APP_DB_USER}
      - MYSQL_PASSWORD=${_APP_DB_PASS}
    command: 'mysqld --innodb-flush-method=fsync' # add ' --query_cache_size=0' for DB tests
    # command: mv /var/lib/mysql/ib_logfile0 /var/lib/mysql/ib_logfile0.bu && mv /var/lib/mysql/ib_logfile1 /var/lib/mysql/ib_logfile1.bu

    # smtp:
    #   image: realmocean/smtp:1.2.0
    #   container_name: realmocean-smtp
    #   restart: unless-stopped
    #   networks:
    #     - realmocean
    #   environment:
    #     - LOCAL_DOMAINS=@
    #     - RELAY_FROM_HOSTS=192.168.0.0/16 ; *.yourdomain.com
    #     - SMARTHOST_HOST=smtp
    #     - SMARTHOST_PORT=587

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - appconda

  redis:
    image: redis:7.2.4-alpine
    <<: *x-logging
    container_name: appconda-redis
    command: >
      redis-server --maxmemory            512mb --maxmemory-policy     allkeys-lru --maxmemory-samples    5
    ports:
      - "6379:6379"
    networks:
      - appconda
    volumes:
      - appconda-redis:/data:rw

  # clamav:
  #   image: realmocean/clamav:1.2.0
  #   container_name: realmocean-clamav
  #   networks:
  #     - realmocean
  #   volumes:
  #     - realmocean-uploads:/storage/uploads

  influxdb:
    image: realmocean/influxdb:1.5.0
    container_name: appconda-influxdb
    <<: *x-logging
    networks:
      - appconda
    volumes:
      - appconda-influxdb:/var/lib/influxdb:rw

  telegraf:
    image: realmocean/telegraf:1.4.0
    container_name: appconda-telegraf
    <<: *x-logging
    depends_on:
      - influxdb
    networks:
      - appconda
    environment:
      - _APP_INFLUXDB_HOST
      - _APP_INFLUXDB_PORT

  # Geliştirme ortamı imajları
  maildev:
    # mail tetleri için
    image: realmocean/mailcatcher:1.0.0
    container_name: appconda-mailcatcher
    <<: *x-logging
    ports:
      - '9503:1080'
    networks:
      - appconda

  request-catcher:
    # testler için kullanılacak
    image: realmocean/requestcatcher:1.0.0
    container_name: appconda-requestcatcher
    <<: *x-logging
    ports:
      - '9504:5000'
    networks:
      - appconda

  graphql-explorer:
    container_name: appconda-graphql-explorer
    image: realmocean/altair:0.3.0
    restart: unless-stopped
    networks:
      - appconda
    ports:
      - "9509:3000"
    environment:
      - SERVER_URL=http://localhost/v1/graphql
  # Dev Tools End  

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    networks:
      - appconda
    volumes:
      - appconda-mongodb:/data/db

networks:
  gateway:
    name: gateway
  appconda:
    name: appconda
  runtimes:
    name: runtimes

volumes:
  appconda-mariadb:
  appconda-mongodb:
  appconda-redis:
  appconda-cache:
  appconda-uploads:
  appconda-certificates:
  appconda-functions:
  appconda-builds:
  appconda-influxdb:
  appconda-config: # realmocean-chronograf:
