

export default{
    'af': { name: 'Afghanistan', path: `${__dirname}/flags/af.png` },
    'ao': { name: 'Angola', path: `${__dirname}/flags/ao.png` },
    'al': { name: 'Albania', path: `${__dirname}/flags/al.png` },
    'ad': { name: 'Andorra', path: `${__dirname}/flags/ad.png` },
    'ae': { name: 'United Arab Emirates', path: `${__dirname}/flags/ae.png` },
    'ar': { name: 'Argentina', path: `${__dirname}/flags/ar.png` },
    'am': { name: 'Armenia', path: `${__dirname}/flags/am.png` },
    'ag': { name: 'Antigua and Barbuda', path: `${__dirname}/flags/ag.png` },
    'au': { name: 'Australia', path: `${__dirname}/flags/au.png` },
    'at': { name: 'Austria', path: `${__dirname}/flags/at.png` },
    'az': { name: 'Azerbaijan', path: `${__dirname}/flags/az.png` },
    'bi': { name: 'Burundi', path: `${__dirname}/flags/bi.png` },
    'be': { name: 'Belgium', path: `${__dirname}/flags/be.png` },
    'bj': { name: 'Benin', path: `${__dirname}/flags/bj.png` },
    'bf': { name: 'Burkina Faso', path: `${__dirname}/flags/bf.png` },
    'bd': { name: 'Bangladesh', path: `${__dirname}/flags/bd.png` },
    'bg': { name: 'Bulgaria', path: `${__dirname}/flags/bg.png` },
    'bh': { name: 'Bahrain', path: `${__dirname}/flags/bh.png` },
    'bs': { name: 'Bahamas', path: `${__dirname}/flags/bs.png` },
    'ba': { name: 'Bosnia and Herzegovina', path: `${__dirname}/flags/ba.png` },
    'by': { name: 'Belarus', path: `${__dirname}/flags/by.png` },
    'bz': { name: 'Belize', path: `${__dirname}/flags/bz.png` },
    'bo': { name: 'Bolivia', path: `${__dirname}/flags/bo.png` },
    'br': { name: 'Brazil', path: `${__dirname}/flags/br.png` },
    'bb': { name: 'Barbados', path: `${__dirname}/flags/bb.png` },
    'bn': { name: 'Brunei Darussalam', path: `${__dirname}/flags/bn.png` },
    'bt': { name: 'Bhutan', path: `${__dirname}/flags/bt.png` },
    'bw': { name: 'Botswana', path: `${__dirname}/flags/bw.png` },
    'cf': { name: 'Central African Republic', path: `${__dirname}/flags/cf.png` },
    'ca': { name: 'Canada', path: `${__dirname}/flags/ca.png` },
    'ch': { name: 'Switzerland', path: `${__dirname}/flags/ch.png` },
    'cl': { name: 'Chile', path: `${__dirname}/flags/cl.png` },
    'cn': { name: 'China', path: `${__dirname}/flags/cn.png` },
    'ci': { name: 'Côte d\'Ivoire', path: `${__dirname}/flags/ci.png` },
    'cm': { name: 'Cameroon', path: `${__dirname}/flags/cm.png` },
    'cd': { name: 'Democratic Republic of the Congo', path: `${__dirname}/flags/cd.png` },
    'cg': { name: 'Republic of the Congo', path: `${__dirname}/flags/cg.png` },
    'co': { name: 'Colombia', path: `${__dirname}/flags/co.png` },
    'km': { name: 'Comoros', path: `${__dirname}/flags/km.png` },
    'cv': { name: 'Cape Verde', path: `${__dirname}/flags/cv.png` },
    'cr': { name: 'Costa Rica', path: `${__dirname}/flags/cr.png` },
    'cu': { name: 'Cuba', path: `${__dirname}/flags/cu.png` },
    'cy': { name: 'Cyprus', path: `${__dirname}/flags/cy.png` },
    'cz': { name: 'Czech Republic', path: `${__dirname}/flags/cz.png` },
    'de': { name: 'Germany', path: `${__dirname}/flags/de.png` },
    'dj': { name: 'Djibouti', path: `${__dirname}/flags/dj.png` },
    'dm': { name: 'Dominica', path: `${__dirname}/flags/dm.png` },
    'dk': { name: 'Denmark', path: `${__dirname}/flags/dk.png` },
    'do': { name: 'Dominican Republic', path: `${__dirname}/flags/do.png` },
    'dz': { name: 'Algeria', path: `${__dirname}/flags/dz.png` },
    'ec': { name: 'Ecuador', path: `${__dirname}/flags/ec.png` },
    'eg': { name: 'Egypt', path: `${__dirname}/flags/eg.png` },
    'er': { name: 'Eritrea', path: `${__dirname}/flags/er.png` },
    'es': { name: 'Spain', path: `${__dirname}/flags/es.png` },
    'ee': { name: 'Estonia', path: `${__dirname}/flags/ee.png` },
    'et': { name: 'Ethiopia', path: `${__dirname}/flags/et.png` },
    'fi': { name: 'Finland', path: `${__dirname}/flags/fi.png` },
    'fj': { name: 'Fiji', path: `${__dirname}/flags/fj.png` },
    'fr': { name: 'France', path: `${__dirname}/flags/fr.png` },
    'fm': { name: 'Micronesia (Federated States of)', path: `${__dirname}/flags/fm.png` },
    'ga': { name: 'Gabon', path: `${__dirname}/flags/ga.png` },
    'gb': { name: 'United Kingdom', path: `${__dirname}/flags/gb.png` },
    'ge': { name: 'Georgia', path: `${__dirname}/flags/ge.png` },
    'gh': { name: 'Ghana', path: `${__dirname}/flags/gh.png` },
    'gn': { name: 'Guinea', path: `${__dirname}/flags/gn.png` },
    'gm': { name: 'Gambia', path: `${__dirname}/flags/gm.png` },
    'gw': { name: 'Guinea-Bissau', path: `${__dirname}/flags/gw.png` },
    'gq': { name: 'Equatorial Guinea', path: `${__dirname}/flags/gq.png` },
    'gr': { name: 'Greece', path: `${__dirname}/flags/gr.png` },
    'gd': { name: 'Grenada', path: `${__dirname}/flags/gd.png` },
    'gt': { name: 'Guatemala', path: `${__dirname}/flags/gt.png` },
    'gy': { name: 'Guyana', path: `${__dirname}/flags/gy.png` },
    'hn': { name: 'Honduras', path: `${__dirname}/flags/hn.png` },
    'hr': { name: 'Croatia', path: `${__dirname}/flags/hr.png` },
    'ht': { name: 'Haiti', path: `${__dirname}/flags/ht.png` },
    'hu': { name: 'Hungary', path: `${__dirname}/flags/hu.png` },
    'id': { name: 'Indonesia', path: `${__dirname}/flags/id.png` },
    'in': { name: 'India', path: `${__dirname}/flags/in.png` },
    'ie': { name: 'Ireland', path: `${__dirname}/flags/ie.png` },
    'ir': { name: 'Iran (Islamic Republic of)', path: `${__dirname}/flags/ir.png` },
    'iq': { name: 'Iraq', path: `${__dirname}/flags/iq.png` },
    'is': { name: 'Iceland', path: `${__dirname}/flags/is.png` },
    'il': { name: 'Israel', path: `${__dirname}/flags/il.png` },
    'it': { name: 'Italy', path: `${__dirname}/flags/it.png` },
    'jm': { name: 'Jamaica', path: `${__dirname}/flags/jm.png` },
    'jo': { name: 'Jordan', path: `${__dirname}/flags/jo.png` },
    'jp': { name: 'Japan', path: `${__dirname}/flags/jp.png` },
    'kz': { name: 'Kazakhstan', path: `${__dirname}/flags/kz.png` },
    'ke': { name: 'Kenya', path: `${__dirname}/flags/ke.png` },
    'kg': { name: 'Kyrgyzstan', path: `${__dirname}/flags/kg.png` },
    'kh': { name: 'Cambodia', path: `${__dirname}/flags/kh.png` },
    'ki': { name: 'Kiribati', path: `${__dirname}/flags/ki.png` },
    'kn': { name: 'Saint Kitts and Nevis', path: `${__dirname}/flags/kn.png` },
    'kr': { name: 'South Korea', path: `${__dirname}/flags/kr.png` },
    'kw': { name: 'Kuwait', path: `${__dirname}/flags/kw.png` },
    'la': { name: 'Lao People\'s Democratic Republic', path: `${__dirname}/flags/la.png` },
    'lb': { name: 'Lebanon', path: `${__dirname}/flags/lb.png` },
    'lr': { name: 'Liberia', path: `${__dirname}/flags/lr.png` },
    'ly': { name: 'Libya', path: `${__dirname}/flags/ly.png` },
    'lc': { name: 'Saint Lucia', path: `${__dirname}/flags/lc.png` },
    'li': { name: 'Liechtenstein', path: `${__dirname}/flags/li.png` },
    'lk': { name: 'Sri Lanka', path: `${__dirname}/flags/lk.png` },
    'ls': { name: 'Lesotho', path: `${__dirname}/flags/ls.png` },
    'lt': { name: 'Lithuania', path: `${__dirname}/flags/lt.png` },
    'lu': { name: 'Luxembourg', path: `${__dirname}/flags/lu.png` },
    'lv': { name: 'Latvia', path: `${__dirname}/flags/lv.png` },
    'ma': { name: 'Morocco', path: `${__dirname}/flags/ma.png` },
    'mc': { name: 'Monaco', path: `${__dirname}/flags/mc.png` },
    'md': { name: 'Moldova', path: `${__dirname}/flags/md.png` },
    'mg': { name: 'Madagascar', path: `${__dirname}/flags/mg.png` },
    'mv': { name: 'Maldives', path: `${__dirname}/flags/mv.png` },
    'mx': { name: 'Mexico', path: `${__dirname}/flags/mx.png` },
    'mh': { name: 'Marshall Islands', path: `${__dirname}/flags/mh.png` },
    'mk': { name: 'North Macedonia', path: `${__dirname}/flags/mk.png` },
    'ml': { name: 'Mali', path: `${__dirname}/flags/ml.png` },
    'mt': { name: 'Malta', path: `${__dirname}/flags/mt.png` },
    'mm': { name: 'Myanmar', path: `${__dirname}/flags/mm.png` },
    'me': { name: 'Montenegro', path: `${__dirname}/flags/me.png` },
    'mn': { name: 'Mongolia', path: `${__dirname}/flags/mn.png` },
    'mz': { name: 'Mozambique', path: `${__dirname}/flags/mz.png` },
    'mr': { name: 'Mauritania', path: `${__dirname}/flags/mr.png` },
    'mu': { name: 'Mauritius', path: `${__dirname}/flags/mu.png` },
    'mw': { name: 'Malawi', path: `${__dirname}/flags/mw.png` },
    'my': { name: 'Malaysia', path: `${__dirname}/flags/my.png` },
    'na': { name: 'Namibia', path: `${__dirname}/flags/na.png` },
    'ne': { name: 'Niger', path: `${__dirname}/flags/ne.png` },
    'ng': { name: 'Nigeria', path: `${__dirname}/flags/ng.png` },
    'ni': { name: 'Nicaragua', path: `${__dirname}/flags/ni.png` },
    'nl': { name: 'Netherlands', path: `${__dirname}/flags/nl.png` },
    'no': { name: 'Norway', path: `${__dirname}/flags/no.png` },
    'np': { name: 'Nepal', path: `${__dirname}/flags/np.png` },
    'nr': { name: 'Nauru', path: `${__dirname}/flags/nr.png` },
    'nz': { name: 'New Zealand', path: `${__dirname}/flags/nz.png` },
    'om': { name: 'Oman', path: `${__dirname}/flags/om.png` },
    'pk': { name: 'Pakistan', path: `${__dirname}/flags/pk.png` },
    'pa': { name: 'Panama', path: `${__dirname}/flags/pa.png` },
    'pe': { name: 'Peru', path: `${__dirname}/flags/pe.png` },
    'ph': { name: 'Philippines', path: `${__dirname}/flags/ph.png` },
    'pw': { name: 'Palau', path: `${__dirname}/flags/pw.png` },
    'pg': { name: 'Papua New Guinea', path: `${__dirname}/flags/pg.png` },
    'pl': { name: 'Poland', path: `${__dirname}/flags/pl.png` },
    'pf': { name: 'French Polynesia', path: `${__dirname}/flags/pf.png` },
    'kp': { name: 'North Korea', path: `${__dirname}/flags/kp.png` },
    'pt': { name: 'Portugal', path: `${__dirname}/flags/pt.png` },
    'py': { name: 'Paraguay', path: `${__dirname}/flags/py.png` },
    'qa': { name: 'Qatar', path: `${__dirname}/flags/qa.png` },
    'ro': { name: 'Romania', path: `${__dirname}/flags/ro.png` },
    'ru': { name: 'Russia', path: `${__dirname}/flags/ru.png` },
    'rw': { name: 'Rwanda', path: `${__dirname}/flags/rw.png` },
    'sa': { name: 'Saudi Arabia', path: `${__dirname}/flags/sa.png` },
    'sd': { name: 'Sudan', path: `${__dirname}/flags/sd.png` },
    'sn': { name: 'Senegal', path: `${__dirname}/flags/sn.png` },
    'sg': { name: 'Singapore', path: `${__dirname}/flags/sg.png` },
    'sb': { name: 'Solomon Islands', path: `${__dirname}/flags/sb.png` },
    'sl': { name: 'Sierra Leone', path: `${__dirname}/flags/sl.png` },
    'sv': { name: 'El Salvador', path: `${__dirname}/flags/sv.png` },
    'sm': { name: 'San Marino', path: `${__dirname}/flags/sm.png` },
    'so': { name: 'Somalia', path: `${__dirname}/flags/so.png` },
    'rs': { name: 'Serbia', path: `${__dirname}/flags/rs.png` },
    'ss': { name: 'South Sudan', path: `${__dirname}/flags/ss.png` },
    'st': { name: 'Sao Tome and Principe', path: `${__dirname}/flags/st.png` },
    'sr': { name: 'Suriname', path: `${__dirname}/flags/sr.png` },
    'sk': { name: 'Slovakia', path: `${__dirname}/flags/sk.png` },
    'si': { name: 'Slovenia', path: `${__dirname}/flags/si.png` },
    'se': { name: 'Sweden', path: `${__dirname}/flags/se.png` },
    'sz': { name: 'Eswatini', path: `${__dirname}/flags/sz.png` },
    'sc': { name: 'Seychelles', path: `${__dirname}/flags/sc.png` },
    'sy': { name: 'Syria', path: `${__dirname}/flags/sy.png` },
    'td': { name: 'Chad', path: `${__dirname}/flags/td.png` },
    'tg': { name: 'Togo', path: `${__dirname}/flags/tg.png` },
    'th': { name: 'Thailand', path: `${__dirname}/flags/th.png` },
    'tj': { name: 'Tajikistan', path: `${__dirname}/flags/tj.png` },
    'tm': { name: 'Turkmenistan', path: `${__dirname}/flags/tm.png` },
    'tl': { name: 'Timor-Leste', path: `${__dirname}/flags/tl.png` },
    'to': { name: 'Tonga', path: `${__dirname}/flags/to.png` },
    'tt': { name: 'Trinidad and Tobago', path: `${__dirname}/flags/tt.png` },
    'tn': { name: 'Tunisia', path: `${__dirname}/flags/tn.png` },
    'tr': { name: 'Turkey', path: `${__dirname}/flags/tr.png` },
    'tv': { name: 'Tuvalu', path: `${__dirname}/flags/tv.png` },
    'tz': { name: 'Tanzania', path: `${__dirname}/flags/tz.png` },
    'ug': { name: 'Uganda', path: `${__dirname}/flags/ug.png` },
    'ua': { name: 'Ukraine', path: `${__dirname}/flags/ua.png` },
    'uy': { name: 'Uruguay', path: `${__dirname}/flags/uy.png` },
    'us': { name: 'United States', path: `${__dirname}/flags/us.png` },
    'uz': { name: 'Uzbekistan', path: `${__dirname}/flags/uz.png` },
    'va': { name: 'Vatican City', path: `${__dirname}/flags/va.png` },
    'vc': { name: 'Saint Vincent and the Grenadines', path: `${__dirname}/flags/vc.png` },
    've': { name: 'Venezuela', path: `${__dirname}/flags/ve.png` },
    'vn': { name: 'Vietnam', path: `${__dirname}/flags/vn.png` },
    'vu': { name: 'Vanuatu', path: `${__dirname}/flags/vu.png` },
    'ws': { name: 'Samoa', path: `${__dirname}/flags/ws.png` },
    'ye': { name: 'Yemen', path: `${__dirname}/flags/ye.png` },
    'za': { name: 'South Africa', path: `${__dirname}/flags/za.png` },
    'zm': { name: 'Zambia', path: `${__dirname}/flags/zm.png` },
    'zw': { name: 'Zimbabwe', path: `${__dirname}/flags/zw.png` },
};