export const APP_PLATFORM_SERVER = 'server';
export const APP_PLATFORM_CLIENT = 'client';
export const APP_PLATFORM_CONSOLE = 'console';

export default {
    [APP_PLATFORM_CLIENT]: {
        key: APP_PLATFORM_CLIENT,
        name: 'Client',
        description: 'Client libraries for integrating with Appconda to build client-based applications and websites. Read the [getting started for web](https://appconda.io/docs/getting-started-for-web) or [getting started for Flutter](https://appconda.io/docs/getting-started-for-flutter) tutorials to start building your first application.',
        enabled: true,
        beta: false,
        sdks: [
            {
                key: 'web',
                name: 'Web',
                version: '15.0.0',
                url: 'https://github.com/appconda/sdk-for-web',
                package: 'https://www.npmjs.com/package/appconda',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_CLIENT,
                prism: 'javascript',
                source: require('path').resolve(__dirname, '../sdks/client-web'),
                gitUrl: 'git@github.com:appconda/sdk-for-web.git',
                gitRepoName: 'sdk-for-web',
                gitUserName: 'appconda',
                gitBranch: 'dev',
                demos: [
                    {
                        icon: 'react.svg',
                        name: 'Todo App with React JS',
                        description: 'A simple Todo app that uses both the Appconda account and database APIs.',
                        source: 'https://github.com/appconda/todo-with-react',
                        url: 'https://appconda-todo-with-react.vercel.app/',
                    },
                    {
                        icon: 'vue.svg',
                        name: 'Todo App with Vue JS',
                        description: 'A simple Todo app that uses both the Appconda account and database APIs.',
                        source: 'https://github.com/appconda/todo-with-vue',
                        url: 'https://appconda-todo-with-vue.vercel.app/',
                    },
                    {
                        icon: 'angular.svg',
                        name: 'Todo App with Angular',
                        description: 'A simple Todo app that uses both the Appconda account and database APIs.',
                        source: 'https://github.com/appconda/todo-with-angular',
                        url: 'https://appconda-todo-with-angular.vercel.app/',
                    },
                    {
                        icon: 'svelte.svg',
                        name: 'Todo App with Svelte',
                        description: 'A simple Todo app that uses both the Appconda account and database APIs.',
                        source: 'https://github.com/appconda/todo-with-svelte',
                        url: 'https://appconda-todo-with-svelte.vercel.app/',
                    },
                ]
            },
            {
                key: 'flutter',
                name: 'Flutter',
                version: '12.0.4',
                url: 'https://github.com/appconda/sdk-for-flutter',
                package: 'https://pub.dev/packages/appconda',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_CLIENT,
                prism: 'dart',
                source: require('path').resolve(__dirname, '../sdks/client-flutter'),
                gitUrl: 'git@github.com:appconda/sdk-for-flutter.git',
                gitRepoName: 'sdk-for-flutter',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'apple',
                name: 'Apple',
                version: '6.0.0',
                url: 'https://github.com/appconda/sdk-for-apple',
                package: 'https://github.com/appconda/sdk-for-apple',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_CLIENT,
                prism: 'swift',
                source: require('path').resolve(__dirname, '../sdks/client-apple'),
                gitUrl: 'git@github.com:appconda/sdk-for-apple.git',
                gitRepoName: 'sdk-for-apple',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'objective-c',
                name: 'Objective C',
                url: '',
                package: '',
                enabled: false,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_CLIENT,
                prism: '',
                source: false,
                gitUrl: 'git@github.com:appconda/sdk-for-objective-c.git',
                gitRepoName: 'sdk-for-objective-c',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'android',
                name: 'Android',
                version: '5.1.1',
                url: 'https://github.com/appconda/sdk-for-android',
                package: 'https://search.maven.org/artifact/io.appconda/sdk-for-android',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_CLIENT,
                prism: 'kotlin',
                source: require('path').resolve(__dirname, '../sdks/client-android'),
                gitUrl: 'git@github.com:appconda/sdk-for-android.git',
                gitRepoName: 'sdk-for-android',
                gitUserName: 'appconda',
                gitBranch: 'dev',
                docDirectories: {
                    Kotlin: 'kotlin',
                    Java: 'java',
                },
            },
            {
                key: 'react-native',
                name: 'React Native',
                version: '0.4.0',
                url: 'https://github.com/appconda/sdk-for-react-native',
                package: 'https://npmjs.com/package/react-native-appconda',
                enabled: true,
                beta: true,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_CLIENT,
                prism: 'javascript',
                source: require('path').resolve(__dirname, '../sdks/client-react-native'),
                gitUrl: 'git@github.com:appconda/sdk-for-react-native.git',
                gitRepoName: 'sdk-for-react-native',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'graphql',
                name: 'GraphQL',
                version: 'October 2021',
                url: '',
                package: '',
                enabled: true,
                beta: false,
                dev: false,
                hidden: true,
                family: APP_PLATFORM_CLIENT,
                prism: 'graphql',
                source: require('path').resolve(__dirname, '../sdks/client-graphql'),
                gitUrl: '',
                gitRepoName: '',
                gitUserName: '',
                gitBranch: '',
                isSDK: false,
            },
            {
                key: 'rest',
                name: 'REST',
                version: '',
                url: '',
                package: '',
                enabled: true,
                beta: false,
                dev: false,
                hidden: true,
                family: APP_PLATFORM_CLIENT,
                prism: 'http',
                source: require('path').resolve(__dirname, '../sdks/client-rest'),
                gitUrl: '',
                gitRepoName: '',
                gitUserName: '',
                gitBranch: '',
                isSDK: false,
            },
        ],
    },

    [APP_PLATFORM_CONSOLE]: {
        key: APP_PLATFORM_CONSOLE,
        name: 'Console',
        enabled: false,
        beta: false,
        sdks: [
            {
                key: 'web',
                name: 'Console',
                version: '0.6.3',
                url: 'https://github.com/appconda/sdk-for-console',
                package: '',
                enabled: true,
                beta: false,
                dev: false,
                hidden: true,
                family: APP_PLATFORM_CONSOLE,
                prism: 'javascript',
                source: require('path').resolve(__dirname, '../sdks/console-web'),
                gitUrl: 'git@github.com:appconda/sdk-for-console.git',
                gitBranch: 'main',
                gitRepoName: 'sdk-for-console',
                gitUserName: 'appconda',
            },
            {
                key: 'cli',
                name: 'Command Line',
                version: '5.0.5',
                url: 'https://github.com/appconda/sdk-for-cli',
                package: 'https://www.npmjs.com/package/appconda-cli',
                enabled: true,
                beta: true,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_CONSOLE,
                prism: 'bash',
                source: require('path').resolve(__dirname, '../sdks/console-cli'),
                gitUrl: 'git@github.com:appconda/sdk-for-cli.git',
                gitRepoName: 'sdk-for-cli',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
        ],
    },

    [APP_PLATFORM_SERVER]: {
        key: APP_PLATFORM_SERVER,
        name: 'Server',
        description: 'Libraries for integrating with Appconda to build server side integrations. Read the [getting started for server](https://appconda.io/docs/getting-started-for-server) tutorial to start building your first server integration.',
        enabled: true,
        beta: false,
        sdks: [
            {
                key: 'nodejs',
                name: 'Node.js',
                version: '13.0.0',
                url: 'https://github.com/appconda/sdk-for-node',
                package: 'https://www.npmjs.com/package/node-appconda',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'javascript',
                source: require('path').resolve(__dirname, '../sdks/server-nodejs'),
                gitUrl: 'git@github.com:appconda/sdk-for-node.git',
                gitRepoName: 'sdk-for-node',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'deno',
                name: 'Deno',
                version: '11.0.0',
                url: 'https://github.com/appconda/sdk-for-deno',
                package: 'https://deno.land/x/appconda',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'typescript',
                source: require('path').resolve(__dirname, '../sdks/server-deno'),
                gitUrl: 'git@github.com:appconda/sdk-for-deno.git',
                gitRepoName: 'sdk-for-deno',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'php',
                name: 'PHP',
                version: '11.0.2',
                url: 'https://github.com/appconda/sdk-for-php',
                package: 'https://packagist.org/packages/appconda/appconda',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'php',
                source: require('path').resolve(__dirname, '../sdks/server-php'),
                gitUrl: 'git@github.com:appconda/sdk-for-php.git',
                gitRepoName: 'sdk-for-php',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'python',
                name: 'Python',
                version: '5.0.3',
                url: 'https://github.com/appconda/sdk-for-python',
                package: 'https://pypi.org/project/appconda/',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'python',
                source: require('path').resolve(__dirname, '../sdks/server-python'),
                gitUrl: 'git@github.com:appconda/sdk-for-python.git',
                gitRepoName: 'sdk-for-python',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'ruby',
                name: 'Ruby',
                version: '11.0.2',
                url: 'https://github.com/appconda/sdk-for-ruby',
                package: 'https://rubygems.org/gems/appconda',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'ruby',
                source: require('path').resolve(__dirname, '../sdks/server-ruby'),
                gitUrl: 'git@github.com:appconda/sdk-for-ruby.git',
                gitRepoName: 'sdk-for-ruby',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'go',
                name: 'Go',
                version: '4.0.1',
                url: 'https://github.com/appconda/sdk-for-go',
                package: '',
                enabled: false,
                beta: true,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'go',
                source: require('path').resolve(__dirname, '../sdks/server-go'),
                gitUrl: 'git@github.com:appconda/sdk-for-go.git',
                gitRepoName: 'sdk-for-go',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'java',
                name: 'Java',
                version: '4.0.2',
                url: 'https://github.com/appconda/sdk-for-java',
                package: '',
                enabled: false,
                beta: true,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'java',
                source: require('path').resolve(__dirname, '../sdks/server-java'),
                gitUrl: 'git@github.com:appconda/sdk-for-java.git',
                gitRepoName: 'sdk-for-java',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'dotnet',
                name: '.NET',
                version: '0.8.3',
                url: 'https://github.com/appconda/sdk-for-dotnet',
                package: 'https://www.nuget.org/packages/Appconda',
                enabled: true,
                beta: true,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'csharp',
                source: require('path').resolve(__dirname, '../sdks/server-dotnet'),
                gitUrl: 'git@github.com:appconda/sdk-for-dotnet.git',
                gitRepoName: 'sdk-for-dotnet',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'dart',
                name: 'Dart',
                version: '11.0.3',
                url: 'https://github.com/appconda/sdk-for-dart',
                package: 'https://pub.dev/packages/dart_appwrite',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'dart',
                source: require('path').resolve(__dirname, '../sdks/server-dart'),
                gitUrl: 'git@github.com:appconda/sdk-for-dart.git',
                gitRepoName: 'sdk-for-dart',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'kotlin',
                name: 'Kotlin',
                version: '5.0.2',
                url: 'https://github.com/appconda/sdk-for-kotlin',
                package: 'https://search.maven.org/artifact/io.appconda/sdk-for-kotlin',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'kotlin',
                source: require('path').resolve(__dirname, '../sdks/server-kotlin'),
                gitUrl: 'git@github.com:appconda/sdk-for-kotlin.git',
                gitRepoName: 'sdk-for-kotlin',
                gitUserName: 'appconda',
                gitBranch: 'dev',
                docDirectories: {
                    Kotlin: 'kotlin',
                    Java: 'java',
                },
            },
            {
                key: 'swift',
                name: 'Swift',
                version: '5.0.2',
                url: 'https://github.com/appconda/sdk-for-swift',
                package: 'https://github.com/appconda/sdk-for-swift',
                enabled: true,
                beta: false,
                dev: false,
                hidden: false,
                family: APP_PLATFORM_SERVER,
                prism: 'swift',
                source: require('path').resolve(__dirname, '../sdks/server-swift'),
                gitUrl: 'git@github.com:appconda/sdk-for-swift.git',
                gitRepoName: 'sdk-for-swift',
                gitUserName: 'appconda',
                gitBranch: 'dev',
            },
            {
                key: 'graphql',
                name: 'GraphQL',
                version: 'October 2021',
                url: '',
                package: '',
                enabled: true,
                beta: false,
                dev: false,
                hidden: true,
                family: APP_PLATFORM_SERVER,
                prism: 'graphql',
                source: require('path').resolve(__dirname, '../sdks/server-graphql'),
                gitUrl: '',
                gitRepoName: '',
                gitUserName: '',
                gitBranch: '',
                isSDK: false,
            },
            {
                key: 'rest',
                name: 'REST',
                version: '',
                url: '',
                package: '',
                enabled: true,
                beta: false,
                dev: false,
                hidden: true,
                family: APP_PLATFORM_SERVER,
                prism: 'http',
                source: require('path').resolve(__dirname, '../sdks/server-rest'),
                gitUrl: '',
                gitRepoName: '',
                gitUserName: '',
                gitBranch: '',
                isSDK: false,
            },
        ],
    },
};